net: ipv4: tcp: remove unused variable 'net'
../net/ipv4/tcp.c:2551:14: error: unused variable 'net' [-Werror,-Wunused-variable]
 2551 |         struct net *net = sock_net(sk);
      |                     ^~~
1 error generated.